# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/176jpJrDtPv6balkwH4TqdRP-jQLGVsZb
"""

pip install pandas

import pandas as pd
id = open("/content/Darknet (1).csv")
df = pd.read_csv(id)
df1 = df.dropna()
df2 = df.fillna("Juan")

def tiempo():
    df2["Timestamp"]=pd.to_datetime(df2["Timestamp"])
    print(df2.columns)
    print(df2.info())

def transformacion():
    for columna in df2.columns:
        try:
            df2[columna] = pd.to_numeric(df2[columna])
            df2[columna].fillna(0, inplace=True)
        except:
            df2[columna] = df2[columna].astype(str)
            df2[columna].fillna("Juan", inplace=True)

    print(df2.describe())

df2["Timestamp"] = pd.to_datetime(df2["Timestamp"])
print(df2.columns)
df2.to_csv("Darknet (1).csv")